### ISSUE TITLE
I cant compile your source in visual studio 2012 ultimate version

### ISSUE THREAD

**Issue by pradeep3093** [risty/SonarLogApi#1]
it shows lot of errors like Invalid token, type expected,unexpected character $ etc.. at first it shows more warnings like framework mismatch i fixed all warnings but i cant fix errors..

**Comment by risty** [comment]
This source code uses .Net 4.6 library and some features of C# 6.0. As far as I can remember, the VS2012 uses a maximum of .Net 4.5 versions. Try to make a downgrade source code to .Net 4.5  or use the VS2017 express.
